### ISSUE TITLE
终看到有DEV+WPF开发的了

### ISSUE THREAD

**Issue by angtianqiang** [lixiaoyuan/JxcApplication#1]
终看到有DEV+WPF开发的了
终看到有DEV+WPF开发的了
终看到有DEV+WPF开发的了
终看到有DEV+WPF开发的了

**Comment by angtianqiang** [comment]
留个联系方式

**Comment by lixiaoyuan** [comment]
@angtianqiang   我这么烂的代码你也要？？？

**Comment by angtianqiang** [comment]
看到都用DEV+WPF开发的，多流个交流的伙伴呢
